<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="$(SolutionDir)ProjectReferences_$(SolutionName).txt" Condition="Exists('$(SolutionDir)ProjectReferences_$(SolutionName).txt')" />

  <Choose>
    <When Condition="Exists('$(HaleyFlowEngineProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyFlowEngineProj)">
          <Name>HaleyFlowEngine</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Flow.Engine" Version="0.0.1" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <Choose>
    <When Condition="Exists('$(HaleyLogProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyLogProj)">
          <Name>HaleyLog</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Log" Version="0.0.1" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <Choose>
    <When Condition="Exists('$(HaleyHelpersProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyHelpersProj)">
          <Name>HaleyHelpers</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Helpers" Version="2.4.1" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <ProjectReference Include="..\..\HaleyFlow.Consumer\HaleyFlowConsumer\HaleyFlowConsumer.csproj" />
    <ProjectReference Include="..\WFE.Lib\WFE.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\WFE.Lib\UseCases\**\*.json" Link="UseCases\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
