<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
  </ItemGroup>
  
  <Import Project="$(SolutionDir)ProjectReferences_$(SolutionName).txt" Condition="Exists('$(SolutionDir)ProjectReferences_$(SolutionName).txt')" />

  <Choose>
    <When Condition="Exists('$(HaleyFlowEngineProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyFlowEngineProj)">
          <Name>HaleyFlowEngine</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Flow.Engine" Version="0.0.1" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <Choose>
    <When Condition="Exists('$(HaleyFlowConsumerProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyFlowConsumerProj)">
          <Name>HaleyFlowConsumer</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Flow.Consumer" Version="0.0.1" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WFE.Lib\WFE.Lib.csproj" />
  </ItemGroup>

</Project>
