<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="$(SolutionDir)ProjectReferences_$(SolutionName).txt" Condition="Exists('$(SolutionDir)ProjectReferences_$(SolutionName).txt')" />

  <Choose>
    <When Condition="Exists('$(HaleyFlowEngineProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyFlowEngineProj)">
          <Name>HaleyFlowEngine</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Flow.Engine" Version="0.0.1" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <Choose>
    <When Condition="Exists('$(HaleyFlowConsumerProj)')">
      <ItemGroup>
        <ProjectReference Include="$(HaleyFlowConsumerProj)">
          <Name>HaleyFlowConsumer</Name>
        </ProjectReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Haley.Flow.Consumer" Version="0.0.1" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <Content Include="UseCases\**\*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

</Project>
